# Weekly Assignment 4
 


## Full name: Jonah Jordan
## R#: 11886590
## Title of the notebook: Assignment 4¶
## Date: 10/16

In [1]:
# Preamble script block to identify host, user, and kernel
import sys
! hostname
! whoami
print(sys.executable)
print(sys.version)
print(sys.version_info)

Jonah_laptop
jonah_laptop\jonah
C:\Users\JONAH\anaconda3\python.exe
3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:38:37) [MSC v.1916 64 bit (AMD64)]
sys.version_info(major=3, minor=11, micro=4, releaselevel='final', serial=0)


## Question1: A Module to Detect the Odd Ones


### Create an external user-defined module (library) that once imported, provides access to a function that for any integer provided by the user, states whether it is an odd number or an even number. This module should be included as a python file (.py) in your submissions. Test your module for five numbers of your own selection and write a paragraph to explain how to solved the problem. 

In [34]:
import numdetector as nd

In [36]:
nd.oddfunc()

Enter an integer: 5
5 is an odd number.


In [37]:
nd.oddfunc()

Enter an integer: 6
6 is an even number.


In [38]:
nd.oddfunc()

Enter an integer: 45986
45986 is an even number.


In [39]:
nd.oddfunc()

Enter an integer: -55
-55 is an odd number.


In [41]:
nd.oddfunc()

Enter an integer: 42
42 is an even number.


For this problem I made a python file in my notebook and wrote the following simple code:
def oddfunc():
    user_input = input("Enter an integer: ")
    num = int(user_input)
    if num % 2 == 0:
            print(f"{num} is an even number.")
    else:
            print(f"{num} is an odd number.")
I made the function oddfunc so that I could call it in my notebook here, I also shortend "numdetector" as "nd" so it would be easier to follow. and in the end it was able to succesfully create the right output.

## Question2: NumPy Playground

### The core datatype of NumPy is the NumPy Array. NumPy Arrays build on the basic Python List datatype to add functionality for vector math and common statistical calculations. The easiest way to create a NumPy Array is to first create a List and then passing it as the argument to the *np.Array()* constructor. In this exercise, you'll create some NumPy arrays, and then perform some simple operations on them.

### Resources
* https://www.w3schools.com/PYTHON/numpy/numpy_creating_arrays.asp
* https://www.w3schools.com/PYTHON/numpy/numpy_array_shape.asp
* https://www.w3schools.com/PYTHON/numpy/numpy_array_sort.asp

### Instructions
1. Create a 1-dimensional Array, named *my_arr* containing the elements **[9,8,7,6,5,4,3,2,1]**.
2. Print the shape of *my_arr*.
3. Create a 2-dimensional Array, named *my_mat* containing rows, each containing a copy of my_arr.
4. Print the shape of *my_mat*.
5. Create a new Array named *my_prod* and use it to store the result of the operation **my_arr * my_arr**.
6. Print out *my_prod*
7. Use the **np.sort** function to sort *my_prod* and store the result in a new Array named *my_prod_sorted*.
8. Print out *my_prod_sorted*

In [46]:
# Question 2 Code Goes Here

import numpy as np

# 1-dimensional array
my_arr = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1])

print("Shape of my_arr:", my_arr.shape)

#  2-dimensional array 
my_mat = np.tile(my_arr, (my_arr.size, 1))

print("Shape of my_mat:", my_mat.shape)

#  new array my_prod 
my_prod = my_arr * my_arr

# Print my_prod
print("my_prod:", my_prod)

#  sort my_prod 
my_prod_sorted = np.sort(my_prod)

# Print my_prod_sorted
print("my_prod_sorted:", my_prod_sorted)

Shape of my_arr: (9,)
Shape of my_mat: (9, 9)
my_prod: [81 64 49 36 25 16  9  4  1]
my_prod_sorted: [ 1  4  9 16 25 36 49 64 81]


## Question3: Matrices

### NumPy really shines when it's time to work with vectors and matrices. A lot of complex operations work right out of the box and are very easy to use. In this exercise, we'll look at how to manipulate the shape of matrices, access their rows and columns, and perform some matrix math operation

* https://www.w3schools.com/PYTHON/numpy/numpy_array_reshape.asp
* https://www.w3schools.com/PYTHON/numpy/numpy_array_indexing.asp
* https://pythonexamples.org/python-numpy-dot-product/

1. In Question 2, you created an array called *my_arr*. Use the **reshape** function to create a 3x3 matrix named *arr_reshaped*.
2. Print out *arr_reshaped* to see the result.
3. Use indexing to print out the last row of the matrix and print out the element at the center of the matrix.
4. Create two 1-dimensional arrays named *X* and *Y* with the elements [3,9,5,4] and [1,8,7,6], respectively.
5. Compute the dot product of *X* and *Y* and print the result.

In [48]:

#  3x3 matrix 
arr_reshaped = my_arr.reshape(3, 3)


print("arr_reshaped:")
print(arr_reshaped)

# last row of the matrix
last_row = arr_reshaped[-1, :]
print("Last row of the matrix:", last_row)

# center of the matrix
center_element = arr_reshaped[1, 1]
print("Element at the center of the matrix:", center_element)

#  two 1-dimensional arrays X and Y
X = np.array([3, 9, 5, 4])
Y = np.array([1, 8, 7, 6])

# product of X and Y
dot_product = np.dot(X, Y)


print("Dot product of X and Y:", dot_product)


arr_reshaped:
[[9 8 7]
 [6 5 4]
 [3 2 1]]
Last row of the matrix: [3 2 1]
Element at the center of the matrix: 5
Dot product of X and Y: 134
