# <font color=darkred>Laboratory 13: Numpy for Bread! (continued...) </font>

In [1]:
# Preamble script block to identify host, user, and kernel
import sys
! hostname
! whoami
print(sys.executable)
print(sys.version)
print(sys.version_info)

Jonah_laptop
jonah_laptop\jonah
C:\Users\JONAH\anaconda3\python.exe
3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:38:37) [MSC v.1916 64 bit (AMD64)]
sys.version_info(major=3, minor=11, micro=4, releaselevel='final', serial=0)


## Full name: Jonah Jordan
## R#: 11886590
## Title of the notebook: lab 13
## Date: 10/4
___

![](https://miro.medium.com/max/450/1*fRAyUZ3-NftpXJf2mb4apw.png) <br>

___
### <font color=purple>Arrays Manipulation</font>

numpy.copy() allows us to create a copy of an array. This is particularly useful when we need to manipulate an array while keeping an original copy in memory.
The numpy.delete() function returns a new array with sub-arrays along an axis deleted. Let's have a look at the examples.


![](https://codetorial.net/numpy/_images/numpy_delete_01.png)
![](https://www.w3resource.com/w3r_images/numpy-manipulation-delete-function-image-1.png)

___
### Example- Copying and Deleting Arrays and Elements
- Define a 1D array, named "x" with [1,2,3]
- Define "y" so that "y=x"
- Define "z" as a copy of "x"
- Discuss the difference between y and z
- Delete the second element of x

In [2]:
import numpy as np         #import numpy

x = np.array([1,2,3])     #Step1: Define x
print(x)

y = x                     #Step2: Define y as y=x
print(y)

z = np.copy(x)            #Step3: Define z as a copy of x
print(z)

[1 2 3]
[1 2 3]
[1 2 3]


In [3]:
# For Step4: They look similar but check this out:
x[1] = 8                  # If we change x ...

print(x) # Guess: 1 8 3
print(y) # Guess: 1 8 3
print(z) # Guess: 1 2 3

[1 8 3]
[1 8 3]
[1 2 3]


In [4]:
# By modifying x, y changes but z remains as a copy of the initial version of x.
y = np.delete(y, 1)      #Step5: Delete the second element of x
print(y) # Guess: 1 3

[1 3]


___
### <font color=purple>Sorting Arrays</font>

Sorting means putting elements in an ordered sequence. Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending. If you use the sort() method on a 2-D array, both arrays will be sorted.

![](https://www.w3resource.com/w3r_images/numpy-sorting-and-searching-image-exercise-1.svg)

___
### Example- Sorting 1D Arrays
__Define a 1D array as ['FIFA 2020','Red Dead Redemption','Fallout','GTA','NBA 2018','Need For Speed'] and print it out. Then, sort the array alphabetically.__


In [5]:
import numpy as np         #import numpy
games = np.array(['FIFA 2020','Red Dead Redemption','Fallout','GTA','NBA 2018','Need For Speed'])
print(games)
print(np.sort(games))

['FIFA 2020' 'Red Dead Redemption' 'Fallout' 'GTA' 'NBA 2018'
 'Need For Speed']
['FIFA 2020' 'Fallout' 'GTA' 'NBA 2018' 'Need For Speed'
 'Red Dead Redemption']


In [9]:
import numpy as np

# Original array
games = np.array(['FIFA 2020', 'Red Dead Redemption', 'Fallout', 'GTA', 'NBA 2018', 'Need For Speed'])

# Sort the original array
sorted_games = np.sort(games)

# Create a 2 by 3 matrix 
matrix_2x3 = np.array([sorted_games[:3], sorted_games[3:]])

print(matrix_2x3)

[['FIFA 2020' 'Fallout' 'GTA']
 ['NBA 2018' 'Need For Speed' 'Red Dead Redemption']]


___
### Example- Sorting n-Dimensional Arrays
__Define a 3x3 array with 17,-6,2,86,-12,0,0,23,12 and print it out. Then, sort the array.__

In [6]:
import numpy as np         #import numpy
a = np.array([[17,-6,2],[86,-12,0],[0,23,12]])
print(a)
print ("Along columns : \n", np.sort(a,axis = 0) ) #This will be sorting in each column
print ("Along rows : \n", np.sort(a,axis = 1) ) #This will be sorting in each row
print ("Sorting by default : \n", np.sort(a) )          #Same as above
print ("Along None Axis : \n", np.sort(a,axis = None) ) #This will be sorted like a 1D array


[[ 17  -6   2]
 [ 86 -12   0]
 [  0  23  12]]
Along columns : 
 [[  0 -12   0]
 [ 17  -6   2]
 [ 86  23  12]]
Along rows : 
 [[ -6   2  17]
 [-12   0  86]
 [  0  12  23]]
Sorting by default : 
 [[ -6   2  17]
 [-12   0  86]
 [  0  12  23]]
Along None Axis : 
 [-12  -6   0   0   2  12  17  23  86]


___
### <font color=purple>Partitioning (Slice) Arrays</font>


Slicing in python means taking elements from one given index to another given index.

We can do slicing like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

![](https://media.geeksforgeeks.org/wp-content/uploads/Numpy1.jpg)

___
### Example- Slicing 1D Arrays
__Define a 1D array as [1,3,5,7,9], slice out the [3,5,7] and print it out.__

In [7]:
import numpy as np         #import numpy
a = np.array([1,3,5,7,9])     #Define the array
print(a)
aslice = a[1:4]             #slice the [3,5,7]
print(aslice)               #print it out


[1 3 5 7 9]
[3 5 7]


___
### Example- Slicing n-Dimensional Arrays
__Define a 5x5 array with "Superman, Batman, Jim Hammond, Captain America, Green Arrow, Aquaman, Wonder Woman, Martian Manhunter, Barry Allen, Hal Jordan, Hawkman, Ray Palmer, Spider Man, Thor, Hank Pym, Solar, Iron Man, Dr. Strange, Daredevil, Ted Kord, Captian Marvel, Black Panther, Wolverine, Booster Gold, Spawn " and print it out. Then:__
- Slice the first column and print it out
- Slice the third row and print it out
- Slice 'Wolverine' and print it out
- Slice a 3x3 array with 'Wonder Woman, Ray Palmer, Iron Man, Martian Manhunter, Spider Man, Dr. Strange, Barry Allen, Thor, Daredevil'

In [12]:
import numpy as np         #import numpy
Superheroes = np.array([['Superman', 'Batman', 'Jim Hammond', 'Captain America', 'Green Arrow'],
               ['Aquaman', 'Wonder Woman', 'Martian Manhunter', 'Barry Allen', 'Hal Jordan'],
               ['Hawkman', 'Ray Palmer', 'Spider Man', 'Thor', 'Hank Pym'],
               ['Solar', 'Iron Man', 'Dr. Strange', 'Daredevil', 'Ted Kord'],
               ['Captian Marvel', 'Black Panther', 'Wolverine', 'Booster Gold', 'Spawn']])
print(Superheroes) #Step1
print(Superheroes[:,1])
print(Superheroes[2,:])
print(Superheroes[4,3])
print(Superheroes[1:5,2:4])
print(Superheroes[4,1])
print(Superheroes[2])      #altered all of the values to check behavior

[['Superman' 'Batman' 'Jim Hammond' 'Captain America' 'Green Arrow']
 ['Aquaman' 'Wonder Woman' 'Martian Manhunter' 'Barry Allen' 'Hal Jordan']
 ['Hawkman' 'Ray Palmer' 'Spider Man' 'Thor' 'Hank Pym']
 ['Solar' 'Iron Man' 'Dr. Strange' 'Daredevil' 'Ted Kord']
 ['Captian Marvel' 'Black Panther' 'Wolverine' 'Booster Gold' 'Spawn']]
['Batman' 'Wonder Woman' 'Ray Palmer' 'Iron Man' 'Black Panther']
['Hawkman' 'Ray Palmer' 'Spider Man' 'Thor' 'Hank Pym']
Booster Gold
[['Martian Manhunter' 'Barry Allen']
 ['Spider Man' 'Thor']
 ['Dr. Strange' 'Daredevil']
 ['Wolverine' 'Booster Gold']]
Black Panther
['Hawkman' 'Ray Palmer' 'Spider Man' 'Thor' 'Hank Pym']


___
## <font color=orange>This is a Numpy Cheat Sheet- similar to the one you had on top of this notebook!</font>

![](https://pbs.twimg.com/media/C2ZI7vSW8AIaZ7g.jpg)

### Check out this link for more: <br>
https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf <br>
https://blog.finxter.com/collection-10-best-numpy-cheat-sheets-every-python-coder-must-own/

___
![](https://media2.giphy.com/media/5nj4ZZWl6QwneEaBX4/source.gif) <br>

*Here are some of the resources used for creating this notebook:* 
- Johnson, J. (2020). Python Numpy Tutorial (with Jupyter and Colab). Retrieved September 15, 2020, from https://cs231n.github.io/python-numpy-tutorial/ <br>
- Willems, K. (2019). (Tutorial) Python NUMPY Array TUTORIAL. Retrieved September 15, 2020, from https://www.datacamp.com/community/tutorials/python-numpy-tutorial?utm_source=adwords_ppc <br>
- Willems, K. (2017). NumPy Cheat Sheet: Data Analysis in Python. Retrieved September 15, 2020, from https://www.datacamp.com/community/blog/python-numpy-cheat-sheet <br>
- W3resource. (2020). NumPy: Compare two given arrays. Retrieved September 15, 2020, from https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-28.php <br>



*Here are some great reads on this topic:* 
- __"Python NumPy Tutorial"__ available at *https://www.geeksforgeeks.org/python-numpy-tutorial/<br>
- __"What Is NumPy?"__ a collection of blogs, available at *https://realpython.com/tutorials/numpy/ <br>
- __"Look Ma, No For-Loops: Array Programming With NumPy"__ by __Brad Solomon__ available at *https://realpython.com/numpy-array-programming/ <br>
- __"The Ultimate Beginner’s Guide to NumPy"__ by __Anne Bonner__ available at *https://towardsdatascience.com/the-ultimate-beginners-guide-to-numpy-f5a2f99aef54 <br>


*Here are some great videos on these topics:* 
- __"Learn NUMPY in 5 minutes - BEST Python Library!"__ by __Python Programmer__ available at *https://www.youtube.com/watch?v=xECXZ3tyONo <br>
- __"Python NumPy Tutorial for Beginners"__ by __freeCodeCamp.org__ available at *https://www.youtube.com/watch?v=QUT1VHiLmmI <br>
- __"Complete Python NumPy Tutorial (Creating Arrays, Indexing, Math, Statistics, Reshaping)"__ by __Keith Galli__ available at *https://www.youtube.com/watch?v=GB9ByFAIAH4 <br>
- __"Python NumPy Tutorial | NumPy Array | Python Tutorial For Beginners | Python Training | Edureka"__ by __edureka!__ available at *https://www.youtube.com/watch?v=8JfDAm9y_7s <br>

___
![](https://media.csesoc.org.au/content/images/2019/10/learn11.gif) <br>


## Exercise: Numpy Arrays – sl***ice*** sl***ice*** baby! <br>

### Modify the given code to do the following.

#### Slice and print given array to look like this:


#### Then calculate the mean of this slice of array using numpy `mean()` function.

#### * Make sure to cite any resources that you may use. 

In [15]:
%reset -f 
import numpy as np

mertsArray = np.array([[1,   2,  3,  4,  5],
                       [6,   7,  8,  9, 10],
                       [11, 12, 13, 14, 15],
                       [16, 17, 18, 19, 20]])

print("mertsArray:")
print(mertsArray)       

print("\n")

slicedMertsArray = mertsArray[1:3, 1:4]

print("A slice of mertsArray:")
print(slicedMertsArray)                        # MODIFY THIS LINE

print("\n")

mean_of_slice = np.mean(slicedMertsArray)
print("mean of the slice:")
print(mean_of_slice)                                      # MODIFY THIS LINE

mertsArray:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


A slice of mertsArray:
[[ 7  8  9]
 [12 13 14]]


mean of the slice:
10.5


![](https://quotefancy.com/media/wallpaper/3840x2160/1750339-Baruch-Spinoza-Quote-No-matter-how-thin-you-slice-it-there-will.jpg)